// <auto-generated />
namespace MVCPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RepoCloned : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RepoCloned));
        
        string IMigrationMetadata.Id
        {
            get { return "202304141422458_Repo Cloned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
